### ISSUE TITLE
make give these errors at the end

### ISSUE THREAD

**Issue by h57jafari** [ShaneFlandermeyer/gr-plasma#5]
I installed plasma-dsp successfully, now during installing gr-plasma, "make" step stop here:
[ 59%] Linking CXX executable plasma_calibrate_delay

and 
[make_error_gr-plasma.odt](https://github.com/ShaneFlandermeyer/gr-plasma/files/12722133/make_error_gr-plasma.odt)
give these errors at the end:

make[2]: *** [apps/CMakeFiles/plasma_calibrate_delay.dir/build.make:131: apps/plasma_calibrate_delay] Error 1
make[1]: *** [CMakeFiles/Makefile2:408: apps/CMakeFiles/plasma_calibrate_delay.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

attached the result from "make" command.
any suggestion?

[make_error_gr-plasma.odt](https://github.com/ShaneFlandermeyer/gr-plasma/files/12722258/make_error_gr-plasma.odt)

**Comment by ShaneFlandermeyer** [comment]
Thanks for putting in an issue. I'm making some changes to both repositories right now, and I expect to have this problem fixed and merged at some point this week.

**Comment by h57jafari** [comment]
Thank you!

**Comment by ShaneFlandermeyer** [comment]
Ok, I've made a bunch of changes and the calibration script builds and works on my machine (famous last words, I know). Try the following steps:

1. Uninstall your current versions of plasma-dsp and gr-plasma
2. Checkout the develop branch of both repos and install as in the readme
3. Hopefully things build. If so you can run the calibration script with a radio in loopback. The command and output of the script should look something like:

```
$ plasma_calibrate_delay --rates=10e6 --tx_gain=50 --rx_gain=40 --freq=2.4e9 --filename=/home/shane/test.txt

ArrayFire v3.8.3 (CUDA, 64-bit Linux, build 987d5675a)
Platform: CUDA Runtime 12.0, Driver: 535.104.05
[0] NVIDIA RTX A6000, 48677 MB, CUDA Compute 8.6
-1- Quadro RTX 5000, 16118 MB, CUDA Compute 7.5
-2- NVIDIA T400, 1860 MB, CUDA Compute 7.5
[INFO] [UHD] linux; GNU C++ version 11.4.0; Boost_107400; DPDK_21.11; UHD_4.5.0.HEAD-0-g471af98f
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Setting master clock rate selection to 'automatic'.
[INFO] [B200] Asking for clock rate 16.000000 MHz... 
[INFO] [B200] Actually got clock rate 16.000000 MHz.
[INFO] [B200] Asking for clock rate 40.000000 MHz... 
[INFO] [B200] Actually got clock rate 40.000000 MHz.
[INFO] [CALIBRATE_DELAY] At MCR = 40 MHz, sample rate = 10 MHz, delay is 46 samples
```

4. If that works and things run successfully, I'll merge the changes into the master branch. I'm hoping these fixes work fine, but I may have to make additional changes to the boost program options as referenced in #3 and #4

**Comment by ShaneFlandermeyer** [comment]
I should additionally note that this script is not required to use the module in GNU Radio, so until things are fully fixed you can comment out the lines in apps/CMakeLists.txt and build as normal

**Comment by h57jafari** [comment]
Hi,

thank you, but it seems that I could not run the "make" successfully, same error:

 {58%] Linking CXX executable plasma_calibrate_delay
/usr/bin/ld: CMakeFiles/plasma_calibrate_delay.dir/calibrate_usrp_delay.cc.o: in function `_main(int, char**)':
...
...
collect2: error: ld returned 1 exit status
make[2]: *** [apps/CMakeFiles/plasma_calibrate_delay.dir/build.make:131: apps/plasma_calibrate_delay] Error 1
make[1]: *** [CMakeFiles/Makefile2:408: apps/CMakeFiles/plasma_calibrate_delay.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
[make_error_gr-plasma_2.odt](https://github.com/ShaneFlandermeyer/gr-plasma/files/12826395/make_error_gr-plasma_2.odt)

**Comment by h57jafari** [comment]
BTW, what command/s need to be commented in apps/CMakeLists.txt?

**Comment by h57jafari** [comment]
I could run it with commenting calibration related options. now while trying to run pulse doppler example, it asks for delay_calibration.json file. without calibration function (since I could not install calibration function), how I can run the pulse doppler example in gnuradio? any suggestion, thank you.

**Comment by ShaneFlandermeyer** [comment]
That build error is strange; I haven't been able to replicate it on any of my computers. I'll try my best to look into it in the near future. There's probably some package that I'm not properly listing in the dependencies.

For the pulse-doppler example, you can just leave the calibration filename field empty in the block. It's optional.

**Comment by h57jafari** [comment]
Thank you for speedy reply/support. with removing that delay calibration json file option, I can run and see range/doppler plot. since I am using USRP X410 with 4 TX and 4 RX channels, how can I choose different channels as TX and RX?

**Comment by ShaneFlandermeyer** [comment]
There currently isn't a way to do multi-channel stuff in the USRP radar block, since my lab is only doing single-channel experiments at the moment.

However, I tried my best to add hooks into the block to make it easy to extend. Looking at the code, here is a mostly complete list of things you would need to change to support multi-channel operation:

- In the block constructor, I have hard-coded tx_channel_nums and rx_channel_nums variables as vectors that just contain channel 0. You could either change what they are hard-coded to or add a parameter so they can be changed in GRC.
- In the receive() method, I have a single pmt variable called rx_data_pmt (and a pointer to it) whose data is pushed to the output port. You could make that a std::vector<pmt::pmt_t> and an associated std::vector<void*> which would be passed to the rx_stream->recv() call.
- In transmit(), I am hard-coding it to only set tx_buffs[0] to the new message data. One could easily expand this so that the buffer index depends on which Tx port you want to update.
- In GRC and the block's yaml, you could add logic that changes the number of message ports based on how many channels you want, like in the built-in uhd blocks. You could also continue using one port and add metadata telling which channel the data belongs to, but that might be a lot of data through one port for the X410.

The benchmark_rate uhd example would be a good place to look for additional info. This would be an awesome feature to have, but I highly doubt I will be able to implement it myself in the near future. Good luck!

**Comment by h57jafari** [comment]
I really appreciate for informative details. Since I could not install delay calibration (I commented out them) and so cannot use it in the gnu radio. If I know my delay through other methods, is there any way that I can insert the delay value to gnu radio directly, any suggestion?

**Comment by ShaneFlandermeyer** [comment]
Yes! The delay depends on the master clock rate and sample rate, so the calibration file is just a json struct that stores the number of samples to chop off for each parameter combination. Here's the calibration file I use for my B210 as an example.

The delay is also only consistent if the start time parameter in the block is nonzero, so I typically set it to 0.1 or 0.2.

```
{
 "B210": [
  {
   "delay": 46,
   "master_clock_rate": 40000000.0,
   "samp_rate": 10000000.0
  },
  {
   "delay": 165,
   "master_clock_rate": 20000000.0,
   "samp_rate": 20000000.0
  },
  {
   "delay": 165,
   "master_clock_rate": 30000000.0,
   "samp_rate": 30000000.0
  },
  {
   "delay": 165,
   "master_clock_rate": 40000000.0,
   "samp_rate": 40000000.0
  },
  {
   "delay": 158,
   "master_clock_rate": 50000000.0,
   "samp_rate": 50000000.0
  }
 ]
}
```

**Comment by h57jafari** [comment]
Thank you. I used this trick and prepared similar json file with my setting, gnu radio accepted and it works. but all the time for range doppler plot it shows large values for range from 0 to 300,000 m or even 1,500,000 m. it may related to delay? and compared to the typical plot with targets at intersection of range and doppler line, I see weird plots as attached. any suggestion? 
![Screenshot from 2023-10-06 13-37-10](https://github.com/ShaneFlandermeyer/gr-plasma/assets/58533979/53d4610b-3c72-4181-b0a9-0830798bc218)

**Comment by ShaneFlandermeyer** [comment]
Looks like that example flowgraph hasn't been updated with my recent changes. Check out the flowgraph I just pushed to develop.

Also, the range axis is so large because it computes it from the PRF you specify (which looks to be 100). The max range on the plot is the unambiguous range, which is c/(2*prf) = 1.5x10^6

**Comment by viktorivan** [comment]
Hi, I have same error

**Comment by 151ashlyn** [comment]
> I installed plasma-dsp successfully, now during installing gr-plasma, "make" step stop here: [ 59%] Linking CXX executable plasma_calibrate_delay
> 
> and [make_error_gr-plasma.odt](https://github.com/ShaneFlandermeyer/gr-plasma/files/12722133/make_error_gr-plasma.odt) give these errors at the end:
> 
> make[2]: *** [apps/CMakeFiles/plasma_calibrate_delay.dir/build.make:131: apps/plasma_calibrate_delay] Error 1 make[1]: *** [CMakeFiles/Makefile2:408: apps/CMakeFiles/plasma_calibrate_delay.dir/all] Error 2 make: *** [Makefile:146: all] Error 2
> 
> attached the result from "make" command. any suggestion?
> 
> [make_error_gr-plasma.odt](https://github.com/ShaneFlandermeyer/gr-plasma/files/12722258/make_error_gr-plasma.odt)

hi,could you please tell me how to fix this issue?i have same problem with you

**Comment by 151ashlyn** [comment]
i have same problem with [h57jafari](https://github.com/h57jafari),i still don't know how to fix it,could you please tell me what to do next?

**Comment by ShaneFlandermeyer** [comment]
The most recent release removes this part of the CMake since it has been such a headache.
